-- MySQL Script generated by MySQL Workbench
-- Mon Aug 22 09:49:42 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Universidade
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Universidade
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Universidade` DEFAULT CHARACTER SET utf8 ;
USE `Universidade` ;

-- -----------------------------------------------------
-- Table `Universidade`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Universidade`.`Usuario` (
  `Matricula` INT NOT NULL,
  `Nome` VARCHAR(60) NOT NULL,
  `CPF` BIGINT NOT NULL,
  `DataNascimento` DATE NOT NULL,
  `Email` VARCHAR(60) NOT NULL,
  `Telefone` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`Matricula`))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `Universidade`.`Aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Universidade`.`Aluno` (
  `Matricula` INT NOT NULL,
  `Ingresso` DATE NOT NULL,
  `Ativo` TINYINT NOT NULL,
  PRIMARY KEY (`Matricula`))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `Universidade`.`Professor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Universidade`.`Professor` (
  `Matricula` INT NOT NULL,
  `Descricao` VARCHAR(256) NOT NULL,
  PRIMARY KEY (`Matricula`))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `Universidade`.`Departamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Universidade`.`Departamento` (
  `idDepartamento` SMALLINT UNSIGNED NOT NULL,
  `NomeDepartamento` VARCHAR(60) NOT NULL,
  `Contato` VARCHAR(60) NOT NULL,
  `MatriculaADM` INT NOT NULL,
  PRIMARY KEY (`idDepartamento`),
  INDEX `fk_Departamento_Usuario1_idx` (`MatriculaADM` ASC))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `Universidade`.`Curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Universidade`.`Curso` (
  `idCurso` SMALLINT UNSIGNED NOT NULL,
  `Departamento` SMALLINT UNSIGNED NOT NULL,
  `Nome` VARCHAR(60) NOT NULL,
  `Descricao` VARCHAR(512) NOT NULL,
  `AnoFundacao` SMALLINT NOT NULL,
  `Ativo` TINYINT NOT NULL,
  PRIMARY KEY (`idCurso`),
  INDEX `fk_Curso_Departamento1_idx` (`Departamento` ASC))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `Universidade`.`Disciplina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Universidade`.`Disciplina` (
  `idDisciplina` INT NOT NULL,
  `Ativo` TINYINT NOT NULL,
  `Nome` VARCHAR(60) NOT NULL,
  `Descricao` VARCHAR(256) NOT NULL,
  `Ementa` TEXT NOT NULL,
  PRIMARY KEY (`idDisciplina`))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `Universidade`.`OfertaDisciplina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Universidade`.`OfertaDisciplina` (
  `Semestre` SMALLINT UNSIGNED NOT NULL,
  `Disciplina` INT NOT NULL,
  `Professor` INT NOT NULL,
  `DiaDaSemana` TINYINT NOT NULL,
  `HoraInicio` SMALLINT NOT NULL,
  `HoraFim` SMALLINT NOT NULL,
  PRIMARY KEY (`Semestre`, `Disciplina`),
  INDEX `fk_OfertaDisciplina_Disciplina1_idx` (`Disciplina` ASC),
  INDEX `fk_OfertaDisciplina_Professor1_idx` (`Professor` ASC))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `Universidade`.`DisciplinasCurso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Universidade`.`DisciplinasCurso` (
  `Curso` SMALLINT UNSIGNED NOT NULL,
  `Disciplina` INT NOT NULL,
  INDEX `fk_DisciplinasCurso_Curso1_idx` (`Curso` ASC),
  INDEX `fk_DisciplinasCurso_Disciplina1_idx` (`Disciplina` ASC),
  PRIMARY KEY (`Curso`, `Disciplina`))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `Universidade`.`DisciplinasAluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Universidade`.`DisciplinasAluno` (
  `Aluno` INT NOT NULL,
  `Semestre` SMALLINT UNSIGNED NOT NULL,
  `Disciplina` INT NOT NULL,
  `NotaP1` TINYINT UNSIGNED NOT NULL,
  `NotaP2` TINYINT UNSIGNED NOT NULL,
  `Aprovado` TINYINT UNSIGNED NOT NULL,
  INDEX `fk_DisciplinasAluno_Aluno1_idx` (`Aluno` ASC))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `Universidade`.`PreRequisitos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Universidade`.`PreRequisitos` (
  `Curso` SMALLINT UNSIGNED NOT NULL,
  `Disciplina` INT NOT NULL,
  `PreRequisito` INT NOT NULL,
  INDEX `fk_PreRequisitos_DisciplinasCurso1_idx` (`Curso` ASC, `Disciplina` ASC),
  INDEX `fk_PreRequisitos_Disciplina1_idx` (`PreRequisito` ASC))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `Universidade`.`AlunoCurso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Universidade`.`AlunoCurso` (
  `Aluno` INT NOT NULL,
  `Curso` SMALLINT UNSIGNED NOT NULL,
  `Ativo` TINYINT NOT NULL,
  INDEX `fk_AlunoCurso_Aluno1_idx` (`Aluno` ASC),
  INDEX `fk_AlunoCurso_Curso1_idx` (`Curso` ASC))
ENGINE = MyISAM;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
