-- MySQL Script generated by MySQL Workbench
-- Sun Aug 21 23:24:37 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema my_helpdesk
-- -----------------------------------------------------
-- Exemplo de modelagem de banco de dados para sistema simples de helpdesk.
-- 
-- Cadastro de usuários e responsáveis, cadastro de pedidos e ordens de serviço.

-- -----------------------------------------------------
-- Schema my_helpdesk
--
-- Exemplo de modelagem de banco de dados para sistema simples de helpdesk.
-- 
-- Cadastro de usuários e responsáveis, cadastro de pedidos e ordens de serviço.
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `my_helpdesk` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
USE `my_helpdesk` ;

-- -----------------------------------------------------
-- Table `my_helpdesk`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `my_helpdesk`.`usuario` (
  `idUsuario` INT NOT NULL,
  `Nome` VARCHAR(60) NOT NULL COMMENT 'Nome completo',
  `doc_id` VARCHAR(14) NOT NULL COMMENT 'CPF/CNPJ/Outro',
  `email` VARCHAR(60) NOT NULL COMMENT 'E-mail para contato',
  `tel` VARCHAR(20) NOT NULL,
  `usr_login` VARCHAR(30) NOT NULL,
  `usr_senha` VARCHAR(128) NOT NULL COMMENT 'Hash da senha.',
  PRIMARY KEY (`idUsuario`))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `my_helpdesk`.`Empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `my_helpdesk`.`Empresa` (
  `idEmpresa` VARCHAR(14) NOT NULL,
  `Nome` VARCHAR(60) NULL,
  `Contato` VARCHAR(64) NULL,
  `Descricao` VARCHAR(512) NULL,
  `Endereco` VARCHAR(128) NULL,
  PRIMARY KEY (`idEmpresa`))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `my_helpdesk`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `my_helpdesk`.`Cliente` (
  `idCliente` INT NOT NULL,
  `Empresa` VARCHAR(14) NOT NULL,
  INDEX `fk_Cliente_table1_idx` (`idCliente` ASC),
  INDEX `fk_Cliente_Empresa1_idx` (`Empresa` ASC),
  PRIMARY KEY (`idCliente`))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `my_helpdesk`.`Departamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `my_helpdesk`.`Departamento` (
  `idDepartamento` INT NOT NULL,
  `Nome` VARCHAR(50) NULL,
  `Contato` VARCHAR(64) NULL,
  `Responsavel` INT NOT NULL,
  `Descricao` VARCHAR(256) NULL,
  PRIMARY KEY (`idDepartamento`, `Responsavel`),
  INDEX `fk_Departamento_Responsavel1_idx` (`Responsavel` ASC))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `my_helpdesk`.`Responsavel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `my_helpdesk`.`Responsavel` (
  `idResponsavel` INT NOT NULL,
  `Departamento` INT NOT NULL,
  `nivelAcesso` TINYINT NULL,
  PRIMARY KEY (`idResponsavel`),
  INDEX `fk_Responsavel_Departamento1_idx` (`Departamento` ASC))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `my_helpdesk`.`Pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `my_helpdesk`.`Pedido` (
  `idPedido` INT NOT NULL,
  `DataSolicitacao` TIMESTAMP NOT NULL,
  `Titulo` VARCHAR(64) NOT NULL,
  `Descricao` TEXT NOT NULL,
  `Cliente` INT NOT NULL,
  `Liberado` TINYINT NOT NULL,
  PRIMARY KEY (`idPedido`),
  INDEX `fk_Pedido_Cliente1_idx` (`Cliente` ASC))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `my_helpdesk`.`AnaliseDePedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `my_helpdesk`.`AnaliseDePedido` (
  `idAnalise` INT NOT NULL AUTO_INCREMENT,
  `Pedido` INT NOT NULL,
  `Responsavel` INT NOT NULL,
  `DataAnalise` TIMESTAMP NOT NULL,
  INDEX `fk_AnaliseDePedido_Pedido1_idx` (`Pedido` ASC),
  INDEX `fk_AnaliseDePedido_Responsavel1_idx` (`Responsavel` ASC),
  PRIMARY KEY (`idAnalise`))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `my_helpdesk`.`OrdemDeServico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `my_helpdesk`.`OrdemDeServico` (
  `idOrdemDeServico` INT NOT NULL,
  `Abertura` TIMESTAMP NOT NULL,
  `Fechamento` DATE NULL,
  `Cliente` INT NOT NULL,
  `Analise` INT NOT NULL,
  `Responsavel` INT NOT NULL,
  `Empresa` VARCHAR(14) NOT NULL,
  PRIMARY KEY (`idOrdemDeServico`),
  INDEX `fk_OrdemDeServico_Cliente1_idx` (`Cliente` ASC),
  INDEX `fk_OrdemDeServico_AnaliseDePedido1_idx` (`Analise` ASC),
  INDEX `fk_OrdemDeServico_Responsavel1_idx` (`Responsavel` ASC),
  INDEX `fk_OrdemDeServico_Empresa1_idx` (`Empresa` ASC))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `my_helpdesk`.`Historico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `my_helpdesk`.`Historico` (
  `idHistorico` INT NOT NULL AUTO_INCREMENT,
  `OrdemDeServico` INT NOT NULL,
  `DataHora` TIMESTAMP NOT NULL,
  `Usuario` INT NOT NULL,
  `Titulo` VARCHAR(128) NOT NULL,
  `Descricao` TEXT NOT NULL,
  PRIMARY KEY (`idHistorico`),
  INDEX `fk_Historico_OrdemDeServico1_idx` (`OrdemDeServico` ASC),
  INDEX `fk_Historico_usuario1_idx` (`Usuario` ASC))
ENGINE = MyISAM;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
